package by.htp.ex.controller;

public enum CommandName {
	GO_TO_BASE_PAGE, GO_TO_LOGINATION_PAGE, GO_TO_REGISTRATION_PAGE, DO_REGISTRATION,
	GO_TO_NEWS_LIST, GO_TO_VIEW_NEWS,
	CHANGE_LOCALE,
	DO_SIGN_IN, DO_SIGN_OUT
}
