package by.itacademy.htp.ex.controller;

public enum CommandName {
	GO_TO_BASE_PAGE, GO_TO_LOGINATION_PAGE, GO_TO_REGISTRATION_PAGE, DO_REGISTRATION,
	GO_TO_NEWS_LIST, GO_TO_VIEW_NEWS, GO_TO_EDIT_NEWS, GO_TO_ADD_NEWS,
	CHANGE_LOCALE,DO_ADD_NEWS,
	DO_SIGN_IN, DO_SIGN_OUT, DO_EDIT_NEWS
}
